import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

// Translations for the Black Trading platform
export const translations = {
  en: {
    // General
    appName: 'Black Trading',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Information',
    locale: 'en-US',

    // Navigation
    dashboard: 'Dashboard',
    charts: 'Charts',
    scanner: 'Scanner',
    alerts: 'Alerts',
    social: 'Social',
    aiAssistant: 'AI Assistant',

    // Timeframes
    timeframe1m: '1m',
    timeframe5m: '5m',
    timeframe15m: '15m',
    timeframe30m: '30m',
    timeframe1h: '1h',
    timeframe4h: '4h',
    timeframe1d: '1D',
    timeframe1w: '1W',
    timeframe1M: '1M',

    // Labels
    timeframeLabel: 'Timeframe:',
    typeLabel: 'Type:',
    updatedLabel: 'Updated:',
    balanceLabel: 'Balance:',
    orderAmount: 'Order Amount:',
    feeLabel: 'Fee (0.1%):',
    totalLabel: 'Total:',
    sizeLabel: 'Size:',
    entryLabel: 'Entry:',
    currentLabel: 'Current:',
    pnlLabel: 'P&L:',
    createdLabel: 'Created:',
    spreadLabel: 'Spread:',
    depthLabel: 'Depth:',
    lastPrice: 'Last Price',
    activeIndicatorsLabel: 'Active Indicators:',

    // Main Dashboard
    tradingDashboard: 'Trading Dashboard',
    welcomeMessage: 'Welcome back! Monitor your portfolio and execute trades efficiently.',
    compactLayout: 'Compact Layout',
    defaultLayout: 'Default Layout',
    reset: 'Reset',
    customize: 'Customize',
    quickActions: 'Quick Actions',
    advancedCharts: 'Advanced Charts',
    marketScanner: 'Market Scanner',
    manageAlerts: 'Manage Alerts',
    socialFeed: 'Social Feed',
    marketDataLive: 'Market Data Live',
    secureConnection: 'Secure Connection',
    lastUpdated: 'Last updated',
    loadingDashboard: 'Loading Dashboard...',
    initializingWorkspace: 'Initializing workspace',

    // Metrics Cards
    marketStatus: 'Market Status',
    accountBalance: 'Account Balance',
    dailyPnL: 'Daily P&L',
    openPositions: 'Open Positions',
    totalMarketCap: 'Total Market Cap',
    marketOpen: 'Market Open',
    marketClosed: 'Market Closed',
    preMarket: 'Pre-Market',

    // Trading Chart
    indicators: 'Indicators',
    draw: 'Draw',
    screenshot: 'Screenshot',
    volume: 'Volume',
    live: 'Live',
    
    // Market Watchlist
    watchlist: 'Watchlist',
    favorites: 'Favorites',
    trending: 'Trending',
    bitcoin: 'Bitcoin',
    ethereum: 'Ethereum',
    cardano: 'Cardano',
    solana: 'Solana',
    polkadot: 'Polkadot',
    pepe: 'Pepe',
    shibaInu: 'Shiba Inu',
    dogecoin: 'Dogecoin',
    viewAllMarkets: 'View All Markets',
    add: 'Add',

    // Portfolio Summary
    portfolio: 'Portfolio',
    pnl: 'P&L',
    available: 'Available',
    positions: 'Positions',
    buy: 'Buy',
    sell: 'Sell',

    // Trading Panel
    quickTrade: 'Quick Trade',
    orderType: 'Order Type',
    market: 'Market',
    limit: 'Limit',
    stop: 'Stop',
    stopLimit: 'Stop-limit',
    price: 'Price',
    enterPrice: 'Enter price',
    quantity: 'Quantity',
    enterQuantity: 'Enter quantity',
    max: 'Max',
    useMax: 'Use Max',
    stopLossOptional: 'Stop-Loss (optional)',
    stopLossPrice: 'Stop-loss price',
    takeProfitOptional: 'Take-Profit (optional)',
    takeProfitPrice: 'Take-profit price',
    orderValue: 'Order Value',
    estFee: 'Est. Fee',
    buySymbol: 'Buy',
    sellSymbol: 'Sell',
    alertEnterQuantity: 'Please enter a quantity',
    alertEnterPriceLimit: 'Please enter a price for the limit order',
    alertOrderPlaced: 'order placed successfully!',
    connected: 'Connected',
    secure: 'Secure',

    // Recent Trades
    tradingActivity: 'Trading Activity',
    recentTrades: 'Recent Trades',
    openOrders: 'Open Orders',
    symbol: 'Symbol',
    side: 'Side',
    time: 'Time',
    status: 'Status',
    filled: 'Filled',
    pending: 'Pending',
    cancelled: 'Cancelled',
    value: 'Value',
    fee: 'Fee',
    type: 'Type',
    last24Hours: 'Last 24 hours',
    openOrdersCount: 'open orders',
    alertOrderCancelled: 'Order successfully cancelled!',

    // Market News
    marketFeed: 'Market Feed',
    news: 'News',
    bullish: 'Bullish',
    bearish: 'Bearish',
    neutral: 'Neutral',
    viewAllNews: 'View All News',
    joinSocialFeed: 'Join Social Feed',

    // Advanced Chart
    advancedChartsTitle: 'Advanced Charts - Trading Platform',
    advancedChartsDescription: 'Professional trading charts with technical analysis, indicators, and drawing tools for traders.',
    alertScreenshotSaved: 'Chart screenshot saved to downloads',
    pineScriptEditor: 'Pine Script Editor',
    pineCustomIndicator: 'Custom Indicator',
    pineMaPeriod: 'MA Period',
    pineSource: 'Source',
    pineBuySignal: 'Buy Signal',
    pineSellSignal: 'Sell Signal',
    pineCreateStrategies: 'Pine Script v5 - Create your own indicators and strategies',
    apply: 'Apply',
    save: 'Save',
    tooltipOpen: 'Open:',
    tooltipHigh: 'High:',
    tooltipLow: 'Low:',
    tooltipClose: 'Close:',
    chartTypeCandles: 'Candles',
    chartTypeLine: 'Line',
    chartTypeArea: 'Area',
    chartTypeBars: 'Bars',
    latency: 'Latency: 0ms',
    symbols: 'Symbols',
    searchSymbols: 'Search symbols...',
    markets: 'Markets',
    searchResults: 'Search Results',
    noSymbolsFound: 'No symbols found',
    favoriteSymbols: 'Favorite Symbols',
    noFavoriteSymbols: 'No favorite symbols',
    addFavoritesHint: 'Add symbols to your favorites for quick access',
    cryptocurrencies: 'Cryptocurrencies',
    stocks: 'Stocks',
    forex: 'Forex',
    online: 'Online',
    trading: 'Trading',
    order: 'Order',
    orders: 'Orders',
    alertInsufficientFunds: 'Insufficient funds to execute the order',
    modify: 'Modify',
    close: 'Close',
    noOpenPositions: 'No open positions',
    activeOrders: 'Active Orders',
    statusFilled: 'FILLED',
    statusPending: 'PENDING',
    statusCancelled: 'CANCELLED',
    noActiveOrders: 'No active orders',
    sideLong: 'LONG',
    sideShort: 'SHORT',
    technicalIndicators: 'Technical Indicators',
    trendIndicators: 'Trend',
    momentumIndicators: 'Momentum',
    volumeIndicators: 'Volume',
    volatilityIndicators: 'Volatility',
    indicatorMA20: 'Moving Average (20)',
    indicatorMA50: 'Moving Average (50)',
    indicatorMA200: 'Moving Average (200)',
    indicatorEMA12: 'Exponential MA (12)',
    indicatorEMA26: 'Exponential MA (26)',
    indicatorBB: 'Bollinger Bands',
    indicatorRSI: 'Relative Strength Index (14)',
    indicatorMACD: 'MACD',
    indicatorStoch: 'Stochastic Oscillator',
    indicatorVolume: 'Trading Volume',
    indicatorVWAP: 'Volume-Weighted Average Price',
    indicatorSupertrend: 'SuperTrend Indicator',
    tools: 'Tools',
    drawingTools: 'Drawing Tools',
    toolTrendline: 'Trend Line',
    toolHorizontalLine: 'Horizontal Line',
    toolVerticalLine: 'Vertical Line',
    toolRectangle: 'Rectangle',
    toolCircle: 'Circle',
    toolFibonacci: 'Fibonacci',
    toolPitchfork: 'Andrews' ,
    toolGannFan: 'Gann Fan',
    pineScript: 'Pine Script',
    orderBook: 'Order Book',
    depth: 'Depth',
    trades: 'Trades',
    size: 'Size',
    total: 'Total',
    count: 'Count',
    realTime: 'Real-time',

    // AI Assistant
    aiWelcomeMessage: 'Hello! I',
    aiErrorMessage: 'Sorry, there was an error processing your request. Please try again.',
    aiAnalyzeAndPredict: 'Analyze {symbol} and predict price movement',
    aiChatCleared: 'Chat cleared. How can I help with market analysis?',
    aiIntelligentAnalysis: 'Intelligent market analysis and trading recommendations',
    clear: 'Clear',
    aiSettings: 'AI Settings',
    analyzing: 'Analyzing...',
    enterPrompt: 'Enter your prompt or select a quick action...',
    marketOverview: 'Market Overview',
    reasoningDepth: 'Reasoning Depth',
    reasoningQuick: 'Quick (minimal reasoning)',
    reasoningLight: 'Light (fast analysis)',
    reasoningMedium: 'Medium (balanced)',
    reasoningDeep: 'Deep (detailed analysis)',
    reasoningDepthTooltip: 'Controls the AI',
    analysisType: 'Analysis Type',
    technicalAnalysis: 'Technical Analysis',
    fundamentalAnalysis: 'Fundamental Analysis',
    hybridAnalysis: 'Hybrid Analysis',
    analysisTypeTooltip: 'Focus of market analysis',
    verbosity: 'Verbosity',
    verbosityLow: 'Concise answers',
    verbosityMedium: 'Medium detail',
    verbosityHigh: 'Detailed answers',
    verbosityTooltip: 'Level of detail in responses',
    includeMarketSentiment: 'Include Market Sentiment',
    includeMarketSentimentTooltip: 'Includes analysis of news and social sentiment',
    recommendations: 'Recommendations',
    recommendationsTip1: '• Use "Quick" for simple questions',
    recommendationsTip2: '• Select "Deep" for complex analysis',
    recommendationsTip3: '• Hybrid analysis provides the best results',
    confidence: 'Confidence: {confidence}%',
    keyInsights: 'Key Insights',
    riskFactors: 'Risk Factors',
    predictionFor: 'Prediction for {symbol}',
    confidencePercentage: '{confidence}% confidence',
    riskLevel: 'Risk Level',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    targets: 'Targets',
    targetPrice: 'Target: ${price}',
    supportPrice: 'Support: ${price}',
    resistancePrice: 'Resistance: ${price}',
    keyFactors: 'Key Factors',
    predictionConfidence: 'Prediction Confidence',
    marketPrediction: 'Market Prediction',
    enterSymbolPlaceholder: 'Or enter symbol',
    predictMarket: 'Predict',
    quickPrompts: 'Quick Prompts',
    marketAnalysis: 'Market Analysis',
    marketAnalysisPrompt: 'Analyze the current state of the US stock market',
    technicalAnalysisPrompt: 'Perform technical analysis for {symbol}',
    marketNews: 'Market News',
    marketNewsPrompt: 'What important news is affecting the market today?',
    riskManagement: 'Risk Management',
    riskManagementPrompt: 'Give advice on risk management in trading',
    open: 'Open',
    growth: 'Bullish',
    fall: 'Bearish',
    neutral: 'Neutral',
    
  },
  ru: {
    // General
    appName: 'Black Trading',
    loading: 'Загрузка...',
    error: 'Ошибка',
    success: 'Успех',
    warning: 'Предупреждение',
    info: 'Информация',
    locale: 'ru-RU',

    // Navigation
    dashboard: 'Панель управления',
    charts: 'Графики',
    scanner: 'Сканер',
    alerts: 'Уведомления',
    social: 'Социальные сети',
    aiAssistant: 'ИИ-ассистент',

    // Timeframes
    timeframe1m: '1м',
    timeframe5m: '5м',
    timeframe15m: '15м',
    timeframe30m: '30м',
    timeframe1h: '1ч',
    timeframe4h: '4ч',
    timeframe1d: '1Д',
    timeframe1w: '1Н',
    timeframe1M: '1М',

    // Labels
    timeframeLabel: 'Таймфрейм:',
    typeLabel: 'Тип:',
    updatedLabel: 'Обновлено:',
    balanceLabel: 'Баланс:',
    orderAmount: 'Сумма ордера:',
    feeLabel: 'Комиссия (0.1%):',
    totalLabel: 'Итого:',
    sizeLabel: 'Размер:',
    entryLabel: 'Вход:',
    currentLabel: 'Текущая:',
    pnlLabel: 'P&L:',
    createdLabel: 'Создан:',
    spreadLabel: 'Спред:',
    depthLabel: 'Глубина:',
    lastPrice: 'Последняя цена',
    activeIndicatorsLabel: 'Активные индикаторы:',

    // Main Dashboard
    tradingDashboard: 'Торговая панель',
    welcomeMessage: 'С возвращением! Отслеживайте свой портфель и эффективно совершайте сделки.',
    compactLayout: 'Компактный вид',
    defaultLayout: 'Стандартный вид',
    reset: 'Сбросить',
    customize: 'Настроить',
    quickActions: 'Быстрые действия',
    advancedCharts: 'Продвинутые графики',
    marketScanner: 'Сканер рынка',
    manageAlerts: 'Управление уведомлениями',
    socialFeed: 'Лента соц. сетей',
    marketDataLive: 'Данные рынка в реальном времени',
    secureConnection: 'Безопасное соединение',
    lastUpdated: 'Последнее обновление',
    loadingDashboard: 'Загрузка панели управления...',
    initializingWorkspace: 'Инициализация рабочего пространства',

    // Metrics Cards
    marketStatus: 'Статус рынка',
    accountBalance: 'Баланс счета',
    dailyPnL: 'Дневной P&L',
    openPositions: 'Открытые позиции',
    totalMarketCap: 'Общая капитализация',
    marketOpen: 'Рынок открыт',
    marketClosed: 'Рынок закрыт',
    preMarket: 'Пре-маркет',

    // Trading Chart
    indicators: 'Индикаторы',
    draw: 'Рисовать',
    screenshot: 'Снимок экрана',
    volume: 'Объем',
    live: 'В реальном времени',

    // Market Watchlist
    watchlist: 'Список наблюдения',
    favorites: 'Избранное',
    trending: 'В тренде',
    bitcoin: 'Bitcoin',
    ethereum: 'Ethereum',
    cardano: 'Cardano',
    solana: 'Solana',
    polkadot: 'Polkadot',
    pepe: 'Pepe',
    shibaInu: 'Shiba Inu',
    dogecoin: 'Dogecoin',
    viewAllMarkets: 'Посмотреть все рынки',
    add: 'Добавить',

    // Portfolio Summary
    portfolio: 'Портфель',
    pnl: 'P&L',
    available: 'Доступно',
    positions: 'Позиции',
    buy: 'Купить',
    sell: 'Продать',

    // Trading Panel
    quickTrade: 'Быстрая сделка',
    orderType: 'Тип ордера',
    market: 'Рыночный',
    limit: 'Лимитный',
    stop: 'Стоп',
    stopLimit: 'Стоп-лимит',
    price: 'Цена',
    enterPrice: 'Введите цену',
    quantity: 'Количество',
    enterQuantity: 'Введите количество',
    max: 'Макс',
    useMax: 'Исп. макс.',
    stopLossOptional: 'Стоп-лосс (опционально)',
    stopLossPrice: 'Цена стоп-лосса',
    takeProfitOptional: 'Тейк-профит (опционально)',
    takeProfitPrice: 'Цена тейк-профита',
    orderValue: 'Стоимость ордера',
    estFee: 'Примерная комиссия',
    buySymbol: 'Купить',
    sellSymbol: 'Продать',
    alertEnterQuantity: 'Пожалуйста, введите количество',
    alertEnterPriceLimit: 'Пожалуйста, введите цену для лимитного ордера',
    alertOrderPlaced: 'ордер успешно размещен!',
    connected: 'Подключено',
    secure: 'Безопасно',

    // Recent Trades
    tradingActivity: 'Торговая активность',
    recentTrades: 'Недавние сделки',
    openOrders: 'Открытые ордера',
    symbol: 'Символ',
    side: 'Сторона',
    time: 'Время',
    status: 'Статус',
    filled: 'Исполнен',
    pending: 'В ожидании',
    cancelled: 'Отменен',
    value: 'Стоимость',
    fee: 'Комиссия',
    type: 'Тип',
    last24Hours: 'Последние 24 часа',
    openOrdersCount: 'открытых ордеров',
    alertOrderCancelled: 'Ордер успешно отменен!',

    // Market News
    marketFeed: 'Лента рынка',
    news: 'Новости',
    bullish: 'Бычий',
    bearish: 'Медвежий',
    neutral: 'Нейтральный',
    viewAllNews: 'Смотреть все новости',
    joinSocialFeed: 'Присоединиться к ленте',

    // Advanced Chart
    advancedChartsTitle: 'Продвинутые графики - Торговая платформа',
    advancedChartsDescription: 'Профессиональные торговые графики с техническим анализом, индикаторами и инструментами рисования для трейдеров.',
    alertScreenshotSaved: 'Скриншот графика сохранен в загрузки',
    pineScriptEditor: 'Редактор Pine Script',
    pineCustomIndicator: 'Пользовательский индикатор',
    pineMaPeriod: 'Период MA',
    pineSource: 'Источник',
    pineBuySignal: 'Сигнал на покупку',
    pineSellSignal: 'Сигнал на продажу',
    pineCreateStrategies: 'Pine Script v5 - Создавайте собственные индикаторы и стратегии',
    apply: 'Применить',
    save: 'Сохранить',
    tooltipOpen: 'Открытие:',
    tooltipHigh: 'Максимум:',
    tooltipLow: 'Минимум:',
    tooltipClose: 'Закрытие:',
    chartTypeCandles: 'Свечи',
    chartTypeLine: 'Линия',
    chartTypeArea: 'Область',
    chartTypeBars: 'Бары',
    latency: 'Задержка: 0мс',
    symbols: 'Символы',
    searchSymbols: 'Поиск символов...',
    markets: 'Рынки',
    searchResults: 'Результаты поиска',
    noSymbolsFound: 'Символы не найдены',
    favoriteSymbols: 'Избранные символы',
    noFavoriteSymbols: 'Нет избранных символов',
    addFavoritesHint: 'Добавьте символы в избранное для быстрого доступа',
    cryptocurrencies: 'Криптовалюты',
    stocks: 'Акции',
    forex: 'Валютные пары',
    online: 'Онлайн',
    trading: 'Торговля',
    order: 'Ордер',
    orders: 'Ордера',
    alertInsufficientFunds: 'Недостаточно средств для выполнения ордера',
    modify: 'Изменить',
    close: 'Закрыть',
    noOpenPositions: 'Нет открытых позиций',
    activeOrders: 'Активные ордера',
    statusFilled: 'ИСПОЛНЕН',
    statusPending: 'ОЖИДАЕТ',
    statusCancelled: 'ОТМЕНЕН',
    noActiveOrders: 'Нет активных ордеров',
    sideLong: 'LONG',
    sideShort: 'SHORT',
    technicalIndicators: 'Технические индикаторы',
    trendIndicators: 'Трендовые',
    momentumIndicators: 'Осцилляторы',
    volumeIndicators: 'Объемные',
    volatilityIndicators: 'Волатильность',
    indicatorMA20: 'Скользящая средняя (20)',
    indicatorMA50: 'Скользящая средняя (50)',
    indicatorMA200: 'Скользящая средняя (200)',
    indicatorEMA12: 'Экспоненциальная MA (12)',
    indicatorEMA26: 'Экспоненциальная MA (26)',
    indicatorBB: 'Полосы Боллинджера',
    indicatorRSI: 'Индекс относительной силы (14)',
    indicatorMACD: 'Схождение/расхождение скользящих средних',
    indicatorStoch: 'Стохастический осциллятор',
    indicatorVolume: 'Объем торгов',
    indicatorVWAP: 'Средневзвешенная по объему цена',
    indicatorSupertrend: 'Индикатор SuperTrend',
    tools: 'Инструменты',
    drawingTools: 'Инструменты рисования',
    toolTrendline: 'Трендовая линия',
    toolHorizontalLine: 'Горизонтальная линия',
    toolVerticalLine: 'Вертикальная линия',
    toolRectangle: 'Прямоугольник',
    toolCircle: 'Круг',
    toolFibonacci: 'Фибоначчи',
    toolPitchfork: 'Вилы Эндрюса',
    toolGannFan: 'Веер Ганна',
    pineScript: 'Pine Script',
    orderBook: 'Стакан заявок',
    depth: 'Стакан',
    trades: 'Сделки',
    size: 'Размер',
    total: 'Сумма',
    count: 'Кол-во',
    realTime: 'Реальное время',

    // AI Assistant
    aiWelcomeMessage: 'Привет! Я ваш ИИ-помощник для анализа рынка. Задавайте вопросы о торговле, анализе акций или используйте быстрые действия ниже.',
    aiErrorMessage: 'Извините, произошла ошибка при обработке вашего запроса. Пожалуйста, попробуйте еще раз.',
    aiAnalyzeAndPredict: 'Проанализируй {symbol} и предскажи движение цены',
    aiChatCleared: 'Чат очищен. Как могу помочь с анализом рынка?',
    aiIntelligentAnalysis: 'Интеллектуальный анализ рынка и торговые рекомендации',
    clear: 'Очистить',
    aiSettings: 'Настройки ИИ',
    analyzing: 'Анализирую...',
    enterPrompt: 'Введите ваш запрос или выберите быстрое действие...',
    marketOverview: 'Обзор рынка',
    reasoningDepth: 'Глубина анализа',
    reasoningQuick: 'Быстрый (минимальное рассуждение)',
    reasoningLight: 'Легкий (быстрый анализ)',
    reasoningMedium: 'Средний (сбалансированный)',
    reasoningDeep: 'Глубокий (детальный анализ)',
    reasoningDepthTooltip: 'Контролирует глубину рассуждений ИИ',
    analysisType: 'Тип анализа',
    technicalAnalysis: 'Технический анализ',
    fundamentalAnalysis: 'Фундаментальный анализ',
    hybridAnalysis: 'Комбинированный анализ',
    analysisTypeTooltip: 'Фокус анализа рынка',
    verbosity: 'Детализация ответов',
    verbosityLow: 'Краткие ответы',
    verbosityMedium: 'Средняя детализация',
    verbosityHigh: 'Подробные ответы',
    verbosityTooltip: 'Уровень детализации в ответах',
    includeMarketSentiment: 'Учитывать настроения рынка',
    includeMarketSentimentTooltip: 'Включает анализ новостей и социальных настроений',
    recommendations: 'Рекомендации',
    recommendationsTip1: '• Используйте "Быстрый" для простых вопросов',
    recommendationsTip2: '• Выберите "Глубокий" для сложного анализа',
    recommendationsTip3: '• Комбинированный анализ дает лучшие результаты',
    confidence: 'Уверенность: {confidence}%',
    keyInsights: 'Ключевые выводы',
    riskFactors: 'Факторы риска',
    predictionFor: 'Прогноз по {symbol}',
    confidencePercentage: '{confidence}% уверенность',
    riskLevel: 'Уровень риска',
    low: 'Низкий',
    medium: 'Средний',
    high: 'Высокий',
    targets: 'Цели',
    targetPrice: 'Цель: ${price}',
    supportPrice: 'Поддержка: ${price}',
    resistancePrice: 'Сопротивление: ${price}',
    keyFactors: 'Ключевые факторы',
    predictionConfidence: 'Достоверность прогноза',
    marketPrediction: 'Прогноз рынка',
    enterSymbolPlaceholder: 'Или введите символ',
    predictMarket: 'Прогноз',
    quickPrompts: 'Быстрые запросы',
    marketAnalysis: 'Анализ рынка',
    marketAnalysisPrompt: 'Проанализируй текущее состояние фондового рынка США',
    technicalAnalysisPrompt: 'Проведи технический анализ {symbol}',
    marketNews: 'Новости рынка',
    marketNewsPrompt: 'Какие важные новости влияют на рынок сегодня?',
    riskManagement: 'Риск-менеджмент',
    riskManagementPrompt: 'Дай советы по управлению рисками в торговле',
    open: 'Открыт',
    growth: 'Рост',
    fall: 'Падение',
    neutral: 'Нейтрально',
  }
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('ru');

  const switchLanguage = (lang) => {
    if (translations[lang]) {
      setCurrentLanguage(lang);
    }
  };

  const t = (key, params = {}) => {
    let translation = translations[currentLanguage][key] || key;
    Object.keys(params).forEach(paramKey => {
      translation = translation.replace(`{${paramKey}}`, params[paramKey]);
    });
    return translation;
  };
  
  const value = {
    currentLanguage,
    switchLanguage,
    t,
    translations: translations[currentLanguage],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
